language: perl
perl:
  - "5.6"
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "dev"
  - "blead"

sudo: false
env: COVERAGE=1

matrix:
  allow_failures:
    - perl: "blead"

before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto

install:
  - cpan-install --deps
  - cpan-install --coverage

before_script:
  - coverage-setup

script:
  - prove -lr -j$(test-jobs) $(test-dirs)

after_success:
  - coverage-report
